---
title: "Lab 1 - Data visualization"
author: "Lauren Valle"
format: pdf
editor: visual
---

## Load Packages

```{r}
#| label: load-packages
#| message: false

library(tidyverse)
library(viridis)
```

## Exercise 1

```{r ex-1}
ggplot(midwest)+
  geom_histogram( aes(popdensity), binwidth = 10000)+
labs(
  x = "Population Density",
  y = "count",
  title = "Population Density of Counties"
)
```

This histogram is right skewed. It looks like there is an outlier in between x=7500 and x = 100000

## Exercise 2

```{r ex-2}
ggplot(data = midwest, 
       mapping = aes(x = percollege, y = percbelowpoverty, color = state)) +
  geom_point()+
  labs(
  x = "Percentage of People with a College Degree",
  y = "Percentage Below Poverty",
  title = "Percentage of People with a College Degree vs 
  Percentage of People Below Poverty by State", 
  color = "Midwestern States"
)+
  scale_color_viridis_d()
```

## Exercise 3

This is a general trend among the states included in the dataset that those below the poverty line are less likely to obtain a college degree. 

## Exercise 4
```{r ex-4}
ggplot(data = midwest, 
       mapping = aes(x = percollege, y = percbelowpoverty, color = state)) +
  geom_smooth(se = FALSE)+
  geom_point(alpha = 0.5)+
  labs(
  x = "Percentage of People with a College Degree",
  y = "Percentage Below Poverty",
  title = "Percentage of People with a College Degree vs 
  Percentage of People Below Poverty by State", 
  color = "Midwestern States"
)+
  facet_wrap("state")

```

## Exercise 5

## Exercise 6

## Exercise 7
